paths:
  database: ./songsdb/songs.db
  media: songs
  web_app: karaokeparty/build/web
  playlist: playlist.json
  song_log: song_log.csv
  suggestion_log: suggestions.csv
  bug_log: bugs.csv

server:
  listen: "0.0.0.0:8080"
  password: abc

logging:
  appenders:
    # An appender named "stdout" that writes to stdout
    stdout:
      kind: console
    # An appender named "requests" that writes to a file with a custom pattern encoder
    file:
      kind: rolling_file
      path: karaoke.log
      policy:
        kind: compound
        trigger:
          kind: size
          limit: 10mb
        roller:
          kind: fixed_window
          base: 1
          count: 5
          pattern: "karaoke.{}.log"
      encoder:
        pattern: "{d} [{f}:{L}] {l} - {h({m})}{n}"

  # Set the default logging level to "warn" and attach the "stdout" appender to the root
  root:
    level: debug
    appenders:
      #      - file
      - stdout
